#!/bin/csh

rm -f pts.all

#get line 1, subst 'IDBPATH=xxx' with 'xxx'
set idb = `sed -n -e 's|IDBPATH \(.*\)|\1|' -e '1p' <imageparams.txt`

cp imageparams.txt pts.all

foreach i (`seq $1 $2`)
	cat $idb/$i/fm.same >> pts.all
end

foreach i (`seq $1 $2`)
	echo $i
	if ( $i == $1 ) then
		cat $i/pts.{same} >> pts.all
	else
		cat $i/pts.{down,same} >> pts.all
	endif
end

mv pts.all stack

