#!/bin/csh
if ($#argv == 1) then
    set last=$1
else
    set last=$2
endif
foreach i (`seq $1 $last`)
echo $i
cd $i
qsub -N lou-s-$i -cwd -V -b y -pe batch 8 make -f thumbs.same -j 8 EXTRA=''
cd ..
end
